# Generated by Django 4.0.2 on 2022-02-26 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('D', 'DONE'), ('C', 'CANCELLED')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('disabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('P', 'PENDING'), ('D', 'DONE'), ('C', 'CANCELLED')], max_length=1, null=True)),
                ('new_status', models.CharField(choices=[('P', 'PENDING'), ('D', 'DONE'), ('C', 'CANCELLED')], max_length=1, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
